console.log("Hello World")
var a=10;
let ac=20
let b="string"
{
    let b=35
    console.log(b)
}
const h1=35
console.log(b)
console.log(h1)
// primitive data types:
// 1. Null
// 2. Number
// 3. String
// 4. Symbol
// 5. Boolean
// 6. BigInt
// 7. Undefined

// Non-Primitive Data Types:
// 1. Object

let a1=null
let b1= 12
let c="string"
let d= Symbol("hello")
let e=true
let f=BigInt("564")
let g=undefined

console.log(typeof(a))
console.log(typeof(d))

const hi={
    "name":"Suryajith",
    "age":21,
    college:"CEC",
}
console.log(hi)
console.log(typeof(hi))
console.log(typeof(hi.name))
console.log(hi.age)
console.log(hi["college"])